GoMoney/Base/GMMainViewController.swift
GoMoney/Common/TabBar/RollingPitTabBar.swift
GoMoney/Common/View/GMButton.swift
GoMoney/Constants/Constant.swift
GoMoney/Navigation/GMTabBarViewController.swift
GoMoney/Scences/Home/HomeViewController.swift

fix: background color

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Common/Chart/Formatter/DayAxisValueFormatter.swift
GoMoney/Common/Chart/Formatter/LineChartXAxisFormatter.swift
GoMoney/Common/InputView/AccessoryView.swift
GoMoney/Common/View/GMLabelSpan.swift
GoMoney/Common/View/GMTextField.swift
GoMoney/Extensions/Date+Extension.swift
GoMoney/Extensions/DateFormatter+Extension.swift
GoMoney/Extensions/Expense+Extension.swift
GoMoney/Extensions/UIFont+Extension.swift
GoMoney/Models/Expense.swift
GoMoney/Navigation/GMTabBarViewController.swift
GoMoney/Scences/Home/View/ChartView.swift
GoMoney/Scences/Home/View/RecentExpenseCell.swift
GoMoney/Scences/Stat/StatBarChartCell.swift
GoMoney/Scences/Stat/StatLineChartCell.swift
GoMoney/Scences/Stat/StatTableCell.swift
GoMoney/Scences/Stat/StatViewController.swift
GoMoney/Service/DataService.swift
GoMoney/ViewModel/Stat/StatViewModel.swift
Podfile
Podfile.lock

- UI for stat screen
- Line chart
- Bar chart
- Top expenses
<p>
</p>

feat: statistics screen

---

GoMoney/Models/Expense.swift

- Change `note` type `String`
- Remove `title` field

fix: change expense structure

---

GoMoney/Common/InputView/ExpenseTextField.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift

- Fix textField not show default value caused by `layoutSubview()`
- Color border on focus
- Add `onChange` callback

fix: expense-textfield not show default value

---

GoMoney/Base/GMViewController.swift
GoMoney/Extensions/Notification+Name.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Stat/StatViewController.swift
Podfile.lock

- refresh UI on new expense/income

feat: refresh UI

---

GoMoney/Common/Chart/Formatter/DayAxisValueFormatter.swift
GoMoney/Common/Chart/Formatter/LineChartXAxisFormatter.swift
GoMoney/Extensions/Expense+Extension.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Home/View/ChartView.swift
GoMoney/Scences/Stat/StatBarChartCell.swift
GoMoney/ViewModel/Home/HomeViewModel.swift

- limit number of pie in `PieChart`
- change `BarChart` bar's color
<p align="center">
</p>

update: piechart, barchart

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Base/GMMainViewController.swift
GoMoney/Extensions/UIViewController+Extension.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/ViewModel/Home/HomeViewModel.swift

- Fix alert extension
- Fix home pie chart

fix: alert, piechart

---

GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Stat/StatViewController.swift
GoMoney/Service/DataService.swift
GoMoney/ViewModel/Home/HomeViewModel.swift

feat: swipe to remove

---

GoMoney/Common/SnackBar/GMSnackBar.swift
GoMoney/Common/View/GMLabel.swift
GoMoney/Scences/AddExpense/AddExpenseField.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Auth/SignIn/SignInPasswordVC.swift
GoMoney/Scences/Auth/View/ButtonAuth.swift
GoMoney/Scences/Auth/View/TextFieldSignUp.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Detail/DetailViewController.swift
GoMoney/Scences/Edit/EditTransactionForm.swift
GoMoney/Scences/Edit/EditViewController.swift
GoMoney/Scences/Onboard/OnboardCell.swift
GoMoney/Scences/Profile/ProfileView.swift
GoMoney/ViewModel/AddExpense/AddExpenseViewModel.swift
GoMoney/ViewModel/Detail/DetailViewModel.swift

fix: font allignment

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Extensions/UIView+Constraint.swift
GoMoney/Extensions/UIViewController+Extension.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Detail/DetailViewController.swift
GoMoney/Scences/Edit/EditViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Service/DataService.swift
GoMoney/ViewModel/Detail/DetailViewModel.swift
Podfile
Podfile.lock

feat: edit transaction

---

GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Common/View/GMLabelAction.swift
GoMoney/Scences/Profile/ProfileViewController.swift

- Add touch effect on action buttons
- Fix duplicated `touchUpInside` target

fix: action touch effect

---

Podfile
Podfile.lock

add: lottie library

---

GoMoney/Extensions/UIViewController+Extension.swift

fix: add icon to snackbar

---

GoMoney/AppDelegate/SceneDelegate.swift
GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Extensions/UIViewController+Extension.swift
GoMoney/Navigation/GMTabBarViewController.swift
GoMoney/Scences/Profile/Tools/ToolsViewController.swift
GoMoney/Scences/Setting/SettingsViewController.swift

fix: some ui changes

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/AppDelegate/SceneDelegate.swift
GoMoney/Extensions/UIViewController+Extension.swift
GoMoney/Info.plist
GoMoney/Scences/BioAuth/BioLockViewController.swift
GoMoney/Scences/Setting/SettingsViewController.swift
GoMoney/Service/BiometricService.swift
Podfile
Podfile.lock

- lock app by faceID ...
<p> 
</p>

feat: add biometric authentification

---

GoMoney/Info.plist

fix: disable dark mode

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Extensions/DateFormatter+Extension.swift
GoMoney/Extensions/Expense+Extension.swift
GoMoney/Extensions/UIViewController+Extension.swift
GoMoney/Models/CurrencyUnit.swift
GoMoney/Models/DateFormat.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Setting/SettingsManager.swift
GoMoney/Scences/Setting/SettingsViewController.swift

- Change currency unit
- Change date format
<p>
</p>

change currency and date format

---

GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Extensions/UIView+Constraint.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Profile/Tools/ToolsViewController.swift

- Fix constraints
- Fix animation in background
- Fix leak memory

fix: constraints, leak, animation

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/GoMoney.entitlements
GoMoney/Service/WidgetService.swift
GoMoney/ViewModel/Home/HomeViewModel.swift
Shared/Model/UserDefaults+AppGroup.swift
Shared/Model/Widget+Kind.swift
WidgetExtension/Assets.xcassets/AccentColor.colorset/Contents.json
WidgetExtension/Assets.xcassets/AppIcon.appiconset/Contents.json
WidgetExtension/Assets.xcassets/Contents.json
WidgetExtension/Assets.xcassets/WidgetBackground.colorset/Contents.json
WidgetExtension/IncomeWidget/IncomeWidget.swift
WidgetExtension/Info.plist
WidgetExtension/WidgetBundle.swift
WidgetExtensionExtension.entitlements

- widget show income and outcome

feat:  income/outcome widget

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Extensions/Date+Extension.swift
GoMoney/Scences/Setting/Cells/SettingFooterView.swift
GoMoney/Scences/Setting/SettingsManager.swift
GoMoney/Scences/Setting/SettingsViewController.swift
GoMoney/Scences/Setting/SyncInterval.swift
GoMoney/Service/SyncManager.swift

- Show last synced time
- Optional interval sync time
<p>
</p>

feat: last synced, sync interval

---

GoMoney.xcodeproj/xcshareddata/xcschemes/GoMoney.xcscheme
GoMoney.xcodeproj/xcshareddata/xcschemes/WidgetExtensionExtension.xcscheme

- add `App` scheme and `Widge` scheme

fix: scheme missing

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Scences/Calculator/Calculator.storyboard
GoMoney/Scences/Calculator/CalculatorViewController.swift
GoMoney/Scences/Profile/Tools/ToolsViewController.swift

- Add calculator in Tools screen

feat: tool calculator

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Common/AsyncImage/AsyncImageView.swift
GoMoney/Common/AsyncImage/ImageLoader.swift
GoMoney/Common/InputView/CategoryPickerInputView.swift
GoMoney/Common/View/GMExpenseIcon.swift
GoMoney/Extensions/Expense+Extension.swift
GoMoney/Models/Expense.swift
GoMoney/Models/TransactionTag.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Home/View/RecentExpenseCell.swift
GoMoney/Service/RemoteService.swift
GoMoney/Service/TagService.swift

- Change `TransactionTag` structure for saving and custom.

fix: tag structure

---

GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Common/View/GMLabelActionView.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Edit/EditViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Setting/SettingsViewController.swift
GoMoney/Scences/Stat/StatViewController.swift
GoMoney/ViewModel/Stat/StatViewModel.swift

- Loading on stat screen
- update some padding
- fix button touches

fix: stat screen start loading, padding

---

GoMoney/Base/GMMainViewController.swift
GoMoney/Common/InputView/ExpenseTextField.swift
GoMoney/Common/View/GMFloatingButton.swift
GoMoney/Common/View/GMImageButton.swift
GoMoney/Extensions/UIColor+Extension.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Auth/SignIn/SignInViewController.swift
GoMoney/Scences/Auth/View/ButtonAuth.swift
GoMoney/Scences/Edit/EditViewController.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Stat/StatBarChartCell.swift

- use actionBackgroundColor in extension

update: action color extension

---

GoMoney/Common/InputView/ExpenseTextField.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Scences/Auth/View/ButtonAuth.swift

fix: action colorCG

---

GoMoney/Common/View/GMLoadingView.swift

update: public loading label

---

GoMoney/Common/AsyncImage/AsyncImageView.swift

- Add function to load image with string URL

update: sync image with url string

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/AppDelegate/AppDelegate.swift
GoMoney/Info.plist
GoMoney/Scences/Auth/SignIn/SignInViewController.swift
GoMoney/Scences/Profile/ProfileView.swift
GoMoney/Service/AuthService.swift
GoMoney/Service/UserManager.swift
Podfile
Podfile.lock

feat: login google

---

GoMoney/Constants/UserDefaultKey.swift
GoMoney/Service/SyncManager.swift
GoMoney/Service/TagService.swift

feat: sync user tags

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Common/Currency/MoneyFormatter.swift
GoMoney/Extensions/Double+Extension.swift
GoMoney/Scences/Home/View/ChartView.swift
GoMoney/Scences/Home/View/MonthlyExpenseView.swift
GoMoney/Scences/Home/View/RecentExpenseCell.swift

format amount with commas: transaction cell, chartView

update: format amount with commas

---

GoMoney/Scences/AddExpense/AddExpenseField.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/AddExpense/AddExpenseViewController.swift
GoMoney/Service/DataService.swift

- Add icon to Category input field

🚸 category field icon

---

GoMoney/Service/AuthService.swift
GoMoney/Service/DataService.swift

- Remove user data on logout:
- UserDefaults
- Realm

remove data on logout

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Models/Expense.swift
GoMoney/Scences/Auth/GMAuthViewController.swift
GoMoney/Scences/Auth/SignIn/SignInPasswordVC.swift
GoMoney/Scences/Auth/SignIn/SignInViewController.swift
GoMoney/Scences/Auth/SignUp/SignUpPasswordVC.swift
GoMoney/Scences/Profile/ProfileViewController.swift
GoMoney/Service/AuthService.swift
GoMoney/Service/DataService.swift
GoMoney/Service/RemoteService.swift
GoMoney/Service/TagService.swift
GoMoney/Service/UserManager.swift

feat: restore user data

---

GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/Detail/DetailView.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Tags/NewTagViewController.swift

change `expense` , `income` to `Expense` , `Income`

fix: capitalize expense type

---

GoMoney/Service/DataService.swift
GoMoney/Service/RemoteService.swift

- get expense by id use `realm.object(ofType:forPrimaryKey)`

fix: get expense by id

---

GoMoney/AppDelegate/AppDelegate.swift
GoMoney/GoMoney.entitlements
GoMoney/Info.plist
Podfile
Podfile.lock

feat: add push notification

---

GoMoney.xcodeproj/project.pbxproj
GoMoney.xcodeproj/xcshareddata/xcschemes/GoMoney.xcscheme
GoMoney/Extensions/Double+Extension.swift
GoMoney/Extensions/String+Extension.swift
GoMoney/Scences/AddExpense/AddExpenseForm.swift

- Seperate amount by comma in amount textfield

fix: amount textfield amount seperate

---

GoMoney/Scences/AddExpense/AddExpenseForm.swift
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/ViewModel/Home/HomeViewModel.swift

update: home swipe to edit

---

GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Profile/ProfileViewController.swift
GoMoney/Scences/Stat/StatViewController.swift

- add animation on `Home`, `Stat`, `Profile` screen

ui: viewWillApear animation

---

GoMoney/Base/GMViewController.swift
GoMoney/Constants/Constant.swift
GoMoney/Scences/Profile/ProfileViewController.swift
GoMoney/Scences/Setting/SettingsViewController.swift

feat: open URL

---

GoMoney.xcodeproj/project.pbxproj
GoMoney/Scences/Home/HomeViewController.swift
GoMoney/Scences/Stat/StatViewController.swift
GoMoney/Scences/ViewAll/ViewAllViewController.swift
GoMoney/Scences/ViewAll/ViewAllViewModel.swift
GoMoney/Service/DataService.swift

- view all transactions screen
- view transaction detail in stat screen

feat: view all transactions

---

WidgetExtension/IncomeWidget/IncomeWidget.swift

fix: income/outcome widget UI

---

GoMoney/Scences/Home/View/RecentExpenseCell.swift

#ui-transation-cell: add note label
